require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
    Max: 20

Metrics/AbcSize:
    Max: 40