module Diagrams
  module Elements # Corrected namespace
    class ClassEntity < ::Dry::Struct
      include Diagrams::Elements::Types # Corrected namespace

      # Attributes
      def name: () -> ::String
      def attributes: () -> ::Array[::String]
      def methods: () -> ::Array[::String]

      # Methods
      def to_h: () -> { name: ::String, attributes: ::Array[::String], methods: ::Array[::String] }
    end
  end
end