module Diagrams
  module Elements
    class Edge < ::Dry::Struct
      include Diagrams::Elements::Types

      # Attributes
      def source_id: () -> ::String
      def target_id: () -> ::String
      def label: () -> ::String?

      # Methods
      # Dry::Struct provides to_h, signature reflects potential nil label removal
      def to_h: () -> { source_id: ::String, target_id: ::String, ?label: ::String }
    end
  end
end