module Diagrams
  module Elements
    class Event < ::Dry::Struct
      include Diagrams::Elements::Types

      # Attributes
      def id: () -> ::String
      def label: () -> ::String?

      # Methods
      def to_h: () -> { id: ::String, ?label: ::String }
    end
  end
end