module Diagrams
  module Elements
    # Represents a section within a Gantt chart, grouping multiple tasks.
    class GanttSection < ::Dry::Struct
      include Elements::Types

      # Attributes
      attr_reader title: String
      attr_reader tasks: Array[Task]

      # Methods
      def initialize: (title: String, ?tasks: Array[Task]) -> void
                     | (Hash[Symbol, untyped]) -> void # Allow hash initialization

      def to_h: () -> Hash[Symbol, String | Array[Hash[Symbol, untyped]]]
    end
  end
end