module Diagrams
  module Elements
    class Slice < ::Dry::Struct
      include Diagrams::Elements::Types

      # Attributes
      def label: () -> ::String
      def value: () -> ::Float

      # Methods
      def to_h: () -> { label: ::String, value: ::Float }
    end
  end
end