module Diagrams
  module Elements # Corrected namespace
    class State < ::Dry::Struct
      include Diagrams::Elements::Types # Corrected namespace

      # Attributes
      def id: () -> ::String
      def label: () -> ::String?

      # Methods
      def to_h: () -> { id: ::String, ?label: ::String }
    end
  end
end